MODULES = jailed
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Youtube
DISPLAY_NAME = Youtube
BUNDLE_ID = com.google.ios.youtube.ipa

Youtube_INJECT_DYLIBS = Cercube.dylib
Youtube_IPA = com.google.ios.youtube.ipa

include $(THEOS_MAKE_PATH)/tweak.mk
