MODULES = jailed
include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Spotify
DISPLAY_NAME = Spotify
BUNDLE_ID = com.spotify.client

Spotify_INJECT_DYLIBS = Spotilife.dylib Sposify.dylib
Spotify_IPA = com.spotify.client.ipa

include $(THEOS_MAKE_PATH)/tweak.mk
